/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false` (hash: b487e2c6975a4eac38e1b450c3fdb8db)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	OMR_PUBLIC_ORIGIN: "https://omr-web-staging.21n.workers.dev";
	DEVICE_CREDENTIAL_WRAPPING_KEY: string;
	EXECUTION_RESULT_WRAPPING_KEY: string;
	PLUGFN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OMR_PUBLIC_ORIGIN" | "DEVICE_CREDENTIAL_WRAPPING_KEY" | "EXECUTION_RESULT_WRAPPING_KEY" | "PLUGFN_ENCRYPTION_KEY">> {}
}
